"""Fail a pull request that is too large to review, unless it carries a waiver.

``uv run python tools/pr_size.py --base <ref> [--head <ref>] [--body-file <path>]``
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import unicodedata
from pathlib import Path

# Google eng-practices, Small CLs: "100 lines is usually a reasonable size for a
# CL, and 1000 lines is usually too large"; "The number of files that a change
# is spread across also affects its size"; a large change needs "consent from
# your reviewers in advance" -- here, the waiver heading below.
WARN_LINES = 400
LIMIT_LINES = 1000
LIMIT_FILES = 30
WAIVER_HEADING = "## Size waiver"

EXCLUDED = (
    "uv.lock",  # generated lockfile
    ".theurian/",  # committed knowledge corpus, generated by the product
    "tools/eval/baseline/",  # recorded evaluation baselines
)


def _excluded(path: str) -> bool:
    return any(path.startswith(p) if p.endswith("/") else path == p for p in EXCLUDED)


def _git(*args: str) -> str:
    return subprocess.run(  # noqa: S603 - argv is git plus CI-supplied refs
        ["git", *args],  # noqa: S607 - resolved via PATH
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def measure(base: str, head: str) -> tuple[int, int, int]:
    span = f"{base}...{head}"
    deleted = set(
        _git("diff", "--no-renames", "--diff-filter=D", "--name-only", "-z", span).split("\0")
    )
    lines = files = 0
    for record in _git("diff", "--no-renames", "--numstat", "-z", span).split("\0"):
        if not record:
            continue
        added, removed, path = record.split("\t", 2)
        if _excluded(path):
            continue
        files += 1
        if path in deleted or added == "-":
            lines += 1  # a deleted or binary file counts as one line
        else:
            lines += int(added) + int(removed)
    commits = int(_git("rev-list", "--count", f"{base}..{head}"))
    return commits, files, lines


_COMMENT = re.compile(r"<!--.*?(?:-->|\Z)", re.DOTALL)  # as tests/ci/test_red_team_sweep_prose.py
_ENTITY = re.compile(r"&(?:#\d+|#[xX][0-9a-fA-F]+|\w+);")
_FENCE = re.compile(r"\s{0,3}(```|~~~)")


def _has_text(line: str) -> bool:
    visible = "".join(c for c in _ENTITY.sub("", line) if unicodedata.category(c) != "Cf")
    return any(c.isalnum() for c in visible)


def waiver(body: str) -> str | None:
    """First line with text under a rendered waiver heading, before any next heading."""
    inside = False
    fence = ""
    for line in _COMMENT.sub("", body).splitlines():
        opened = _FENCE.match(line)
        if opened and not fence:
            fence = opened.group(1)
            continue
        if fence:
            fence = "" if opened and opened.group(1) == fence else fence
            continue
        stripped = line.strip()
        if not inside:
            inside = (
                not line.startswith(("    ", "\t")) and stripped.lower() == WAIVER_HEADING.lower()
            )
        elif stripped.startswith("#"):
            return None
        elif _has_text(stripped):
            return stripped
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True)
    parser.add_argument("--head", default="HEAD")
    parser.add_argument("--body-file")
    args = parser.parse_args(argv)

    commits, files, lines = measure(args.base, args.head)
    print(
        f"pr-size: commits={commits} files={files} lines={lines} "
        f"(warn >{WARN_LINES} lines, limit {LIMIT_LINES} lines or {LIMIT_FILES} files)"
    )
    over = []
    if lines > LIMIT_LINES:
        over.append(f"lines {lines} exceeds the limit of {LIMIT_LINES}")
    if files > LIMIT_FILES:
        over.append(f"files {files} exceeds the limit of {LIMIT_FILES}")
    if not over:
        if lines > WARN_LINES:
            print(f"warning: {lines} changed lines is above {WARN_LINES}; consider splitting")
        return 0
    body = Path(args.body_file).read_text(encoding="utf-8") if args.body_file else ""
    reason = waiver(body)
    if reason is not None:
        print(f"waived: {reason}")
        return 0
    print(f"error: {'; '.join(over)}; split the change or add a '{WAIVER_HEADING}' section")
    return 1


if __name__ == "__main__":
    sys.exit(main())
