"""Fail a pull request that is too large to review, unless it carries a waiver.

``uv run python tools/pr_size.py --base <ref> [--head <ref>] [--body-file <path>]``
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import unicodedata
from pathlib import Path

# Google eng-practices, Small CLs: "100 lines is usually a reasonable size for a
# CL, and 1000 lines is usually too large"; "The number of files that a change
# is spread across also affects its size"; a large change needs "consent from
# your reviewers in advance" -- here, the waiver heading below.
WARN_LINES = 400
LIMIT_LINES = 1000
LIMIT_FILES = 30
WAIVER_HEADING = "## Size waiver"

EXCLUDED = (
    "uv.lock",  # generated lockfile
    ".theurian/",  # committed knowledge corpus, generated by the product
    "tools/eval/baseline/",  # recorded evaluation baselines
)


def _excluded(path: str) -> bool:
    return any(path.startswith(p) if p.endswith("/") else path == p for p in EXCLUDED)


def _git(*args: str) -> str:
    return subprocess.run(  # noqa: S603 - argv is git plus CI-supplied refs
        ["git", *args],  # noqa: S607 - resolved via PATH
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def measure(base: str, head: str) -> tuple[int, int, int]:
    span = f"{base}...{head}"
    deleted = set(
        _git("diff", "--no-renames", "--diff-filter=D", "--name-only", "-z", span).split("\0")
    )
    lines = files = 0
    for record in _git("diff", "--no-renames", "--numstat", "-z", span).split("\0"):
        if not record:
            continue
        added, removed, path = record.split("\t", 2)
        if _excluded(path):
            continue
        files += 1
        if path in deleted or added == "-":
            lines += 1  # a deleted or binary file counts as one line
        else:
            lines += int(added) + int(removed)
    commits = int(_git("rev-list", "--count", f"{base}..{head}"))
    return commits, files, lines


_ENTITY = re.compile(r"&(?:#\d+|#[xX][0-9a-fA-F]+|\w+);")
_MARKUP = re.compile(r"!?\[[^\]]*\]\([^)]*\)|<[^>]*>")
_FILLERS = "\u115f\u1160\u3164\uffa0"  # blank-looking letters, category Lo


def _visible_lines(body: str) -> list[str]:
    """Body lines minus comments that start at column 0; an unclosed one hides the rest."""
    kept, hidden = [], False
    for line in body.splitlines():
        hidden = hidden or line.startswith("<!--")
        if not hidden:
            kept.append(line)
        hidden = hidden and "-->" not in line
    return kept


def _has_text(line: str) -> bool:
    visible = _ENTITY.sub("", _MARKUP.sub("", line))
    visible = "".join(c for c in visible if unicodedata.category(c) != "Cf" and c not in _FILLERS)
    return any(c.isalnum() for c in visible)


def _fenced(line: str) -> bool:
    return "```" in line or "~~~" in line


def waiver(body: str) -> str | None:
    """The reason under a column-0 waiver heading, or None.

    Nothing that can open a code context may precede the heading, so the reader
    never has to model rendering.
    """
    inside = False
    for line in _visible_lines(body):
        stripped = line.strip()
        if _fenced(line):
            return None
        if not inside:
            inside = line.rstrip().lower() == WAIVER_HEADING.lower()
        elif stripped.startswith("#"):
            return None
        elif _has_text(stripped):
            return stripped
    return None


def fence_precedes_heading(body: str) -> bool:
    for line in _visible_lines(body):
        if line.rstrip().lower() == WAIVER_HEADING.lower():
            return False
        if _fenced(line):
            return True
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True)
    parser.add_argument("--head", default="HEAD")
    parser.add_argument("--body-file")
    args = parser.parse_args(argv)

    commits, files, lines = measure(args.base, args.head)
    print(
        f"pr-size: commits={commits} files={files} lines={lines} "
        f"(warn >{WARN_LINES} lines, limit {LIMIT_LINES} lines or {LIMIT_FILES} files)"
    )
    over = []
    if lines > LIMIT_LINES:
        over.append(f"lines {lines} exceeds the limit of {LIMIT_LINES}")
    if files > LIMIT_FILES:
        over.append(f"files {files} exceeds the limit of {LIMIT_FILES}")
    if not over:
        if lines > WARN_LINES:
            print(f"warning: {lines} changed lines is above {WARN_LINES}; consider splitting")
        return 0
    body = Path(args.body_file).read_text(encoding="utf-8") if args.body_file else ""
    reason = waiver(body)
    if reason is not None:
        print(f"waived: {reason}")
        return 0
    print(
        f"error: {'; '.join(over)}; split the change or add a '{WAIVER_HEADING}' section "
        "(editing the body starts no run; push a commit or close and reopen)"
    )
    if fence_precedes_heading(body):
        print(f"error: a code fence precedes the heading; put '{WAIVER_HEADING}' above any code")
    return 1


if __name__ == "__main__":
    sys.exit(main())
